//
//  HTTP+Path.swift
//  
//
//  Created by Gregory Higley on 4/4/20.
//

public extension HTTP {
  /**
   Set the already percent-encoded path of the `URLRequest`
   generated by the fluent interface, combined with the
   base URL set in the `HTTPClient`.
   
   ```swift
   let baseURL = "https://httpbin.org/foo"
   HTTPClient(baseURL: baseURL)
    .path(percentEncoded: "bar%40")
   ```
  
   This results in the URL `https://httpbin.org/foo/bar%40`.
   */
  func path(percentEncoded path: String) -> Builder {
    build(\._path, path)
  }

  /**
   A convenient method for setting the path of the
   HTTP request generated by the fluent interface.
   The segments should _not_ be percent-encoded.
   
   ```swift
   let baseURL = "https://httpbin.org"
   HTTPClient(baseURL: baseURL)
    .path("status", 500)
   ```
   
   This results in the URL `https://httpbin.org/status/500`.
   */
  func path(_ segments: Any...) -> Builder {
    path(percentEncoded: segments.map { "\($0)" }.joined(separator: "/"))
  }
}
